service: serverless-bert-lambda-docker

provider:
  name: aws # provider
  region: us-east-1 # aws region
  memorySize: 3008 # optional, in MB, default is 1024
  timeout: 100 # optional, in seconds, default is 6

functions:
  questionanswering:
    image: 503872985149.dkr.ecr.us-east-1.amazonaws.com/summary:latest #ecr url
    events:
      - http:
          path: qa # http path
          method: post # http method
